name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and capture results
        run: |
          npm test > test-results.txt 2>&1 || true

      - name: Upload test results artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt

  deploy:
    name: Deploy Application
    runs-on: self-hosted   
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download test results artifact
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./artifacts

      - name: Display test results
        run: cat ./artifacts/test-results.txt

      - name: Deploy Node.js Application
        run: |
          echo "Deploying Node.js app on self-hosted runner..."
          # Add your deployment commands here, for example:
          # pm2 restart your-app
          # or npm start
