name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests and capture results
        shell: powershell
        run: |
          npm run check > test-results.txt 2>&1

      - name: Upload test results artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
      name: Deploy Application
      needs: test
      runs-on: [self-hosted, windows, x64]

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Download test results artifact
          uses: actions/download-artifact@v4
          with:
            name: test-results
            path: .

        - name: Display test results
          shell: powershell
          run: Get-Content test-results.txt

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Install dependencies
          run: npm install

        - name: Stop existing Node processes
          shell: powershell
          run: |
            Write-Host "Stopping any existing Node servers…"
            Get-Process node -ErrorAction SilentlyContinue | Stop-Process -Force || Write-Host "No node processes found."

        - name: Start application
          shell: powershell
          run: |
            Write-Host "Launching src/server.js…"
            Set-Location $Env:GITHUB_WORKSPACE
            Start-Process node -ArgumentList 'src/server.js' -NoNewWindow

        - name: Wait for service to boot
          shell: powershell
          run: Start-Sleep -Seconds 5

        - name: Health-check
          shell: powershell
          run: |
            try {
              $res = Invoke-RestMethod http://localhost:3000/api
              Write-Host "API OK:" $res.message
            } catch {
              Write-Error "Health-check failed"
              exit 1
            }